services:
  web:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./
          action: rebuild
        - path: .
          target: /app
          action: sync
